name: ci

on:
    push:
        branches:
            - "main"

jobs:
    commands:
        name: thing
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Commands
              uses: actions/checkout@v4
              uses: oven-sh/setup-bun@v1
              run: bun run cmd
              run: bun run cmd-dev
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/hunter-bot:latest
