name: ci

on:
    push:
        branches:
            - "main"

jobs:
    commands:
        name: Deploy Commands
        runs-on: ubuntu-latest
        env:
          TOKEN: ${{secrets.TOKEN}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
        steps:
              - uses: actions/checkout@v4
              - uses: oven-sh/setup-bun@v1
              - run: bun install
              - run: bun run db-gen
              - run: bun run cmd
              - run: bun run cmd-dev
    Docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/hunter-bot:latest
